### ISSUE TITLE
using preferred modules 

### ISSUE THREAD

**Issue by aliatikgit6** [fikrikarim/gitfeed#2]
Hi Fikri , im Ali from adakerja 
could you please do the test and using "redux && (redux-saga || redux-thunk)" for state management also using react-native-cli not expo-cli
and also we don't need react-native web

**Comment by fikrikarim** [comment]
Hi @aliatikgit6 . Thanks for the response. Sorry I didn't know I have to include those libraries. Alright I'll try to find some time and update the project as needed :)

**Comment by aliatikgit6** [comment]
hi @fikrikarim , no need then .we just evaluate from what you have done .

**Comment by fikrikarim** [comment]
Hi @aliatikgit6. I'm really sorry. I had familiy meetings during the weekend. So I just had time to update the project last night.

I just created a [PR to fulfill your request](https://github.com/fikrikarim/gitfeed/pull/3).

You can check the PR to see the changes. Or you can also see in the master branch to see the completed code.

There's no component testing yet. Because most of the code are in screens, and not refactored into component yet. Instead I build the end to end testing using detox.

I haven't changed many of the code to use the redux state management because I haven't got enough time. But I change some of them to demonstrate the usage of redux in the project. Hope it's enough for the evaluation.

Thanks a lot.

Fikri Karim

**Comment by fikrikarim** [comment]
@aliatikgit6 Please pull the repository on your local to see the latest changes. Sorry If I took sometime to update the project.

**Comment by aliatikgit6** [comment]
@fikrikarim sure.

**Comment by fikrikarim** [comment]
Hi @aliatikgit6, is there any update on my application? Sorry If I ask too early.. Just want to know maybe there's any progress for the application. Thanks a lot :)
